version: '3.9'

services:
 proxy:
  build:
    context: .
  environment:
    - API_SERVICE_PORT=${API_SERVICE_PORT}
    - NGINX_LISTEN_PORT=${NGINX_LISTEN_PORT}
    - MAITOCODE_PORT=${MAITOCODE_PORT}
  restart: unless-stopped
  ports:
    - ${NGINX_LISTEN_PORT}:${NGINX_LISTEN_PORT}
  networks:
    - maito-proxy
    - maito-server_maito-server
  external_links:
    - pgadmin:pgadmin
    - src:src
networks:
  maito-proxy:
    driver: bridge
  maito-server_maito-server:
    external: true
  # maitocode_maitocode:
  #   external: true