version: '3.9'

services:
 proxy:
  build:
    context: .
  environment:
    - API_SERVICE_PORT=${API_SERVICE_PORT}
    - NGINX_LISTEN_PORT=${NGINX_LISTEN_PORT}
    - MAITOCODE_PORT=80
  restart: always
  ports:
    - 80:${NGINX_LISTEN_PORT}
  networks:
    - maito-proxy
  external_links:
    - pgadmin:pgadmin
    - src:src
    - maitocode:maitocode
networks:
  maito-proxy:
    driver: bridge