name: maito-proxy runner

on:
  push:
    branches: [master]

jobs:
  test_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set env
        run: cp ~/.env.proxy ~/maito-proxy/_work/maito-proxy/maito-proxy/.env
      - name: Down Containers
        run: docker-compose down || true
      - name: Build
        run: docker-compose build
      - name: run
        run: docker-compose up -d
